-- Gas Cost Report Database Schema


CREATE SEQUENCE IF NOT EXISTS replay_block_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS replay_blocks (
    block_number               BIGINT      NOT NULL,
    block_hash                 CHAR(66)    NOT NULL,
    block_id                   BIGINT      NOT NULL,
    CONSTRAINT replay_blocks_pkey
        PRIMARY KEY (block_number, block_hash),
    CONSTRAINT replay_blocks_block_id_unique
        UNIQUE (block_id)
);


CREATE TABLE IF NOT EXISTS replay_block_transactions (
    block_id                   BIGINT      NOT NULL,
    transaction_index_in_block INTEGER     NOT NULL,
    transaction_hash           CHAR(66)    NOT NULL,
    succeeded                  BOOLEAN     NOT NULL,
    gas_used                   BIGINT      NOT NULL,
    access_list_address_count  INTEGER     NOT NULL,
    access_list_storage_slot_count INTEGER NOT NULL
);


CREATE TABLE IF NOT EXISTS replay_call_opcode_counts (
    block_id                   BIGINT      NOT NULL,
    transaction_index_in_block INTEGER     NOT NULL,

    -- indices 0..255: raw EVM opcode execution counts (opcode_{hex byte})
    opcode_00 INTEGER NOT NULL DEFAULT 0, opcode_01 INTEGER NOT NULL DEFAULT 0,
    opcode_02 INTEGER NOT NULL DEFAULT 0, opcode_03 INTEGER NOT NULL DEFAULT 0,
    opcode_04 INTEGER NOT NULL DEFAULT 0, opcode_05 INTEGER NOT NULL DEFAULT 0,
    opcode_06 INTEGER NOT NULL DEFAULT 0, opcode_07 INTEGER NOT NULL DEFAULT 0,
    opcode_08 INTEGER NOT NULL DEFAULT 0, opcode_09 INTEGER NOT NULL DEFAULT 0,
    opcode_0a INTEGER NOT NULL DEFAULT 0, opcode_0b INTEGER NOT NULL DEFAULT 0,
    opcode_0c INTEGER NOT NULL DEFAULT 0, opcode_0d INTEGER NOT NULL DEFAULT 0,
    opcode_0e INTEGER NOT NULL DEFAULT 0, opcode_0f INTEGER NOT NULL DEFAULT 0,
    opcode_10 INTEGER NOT NULL DEFAULT 0, opcode_11 INTEGER NOT NULL DEFAULT 0,
    opcode_12 INTEGER NOT NULL DEFAULT 0, opcode_13 INTEGER NOT NULL DEFAULT 0,
    opcode_14 INTEGER NOT NULL DEFAULT 0, opcode_15 INTEGER NOT NULL DEFAULT 0,
    opcode_16 INTEGER NOT NULL DEFAULT 0, opcode_17 INTEGER NOT NULL DEFAULT 0,
    opcode_18 INTEGER NOT NULL DEFAULT 0, opcode_19 INTEGER NOT NULL DEFAULT 0,
    opcode_1a INTEGER NOT NULL DEFAULT 0, opcode_1b INTEGER NOT NULL DEFAULT 0,
    opcode_1c INTEGER NOT NULL DEFAULT 0, opcode_1d INTEGER NOT NULL DEFAULT 0,
    opcode_1e INTEGER NOT NULL DEFAULT 0, opcode_1f INTEGER NOT NULL DEFAULT 0,
    opcode_20 INTEGER NOT NULL DEFAULT 0, opcode_21 INTEGER NOT NULL DEFAULT 0,
    opcode_22 INTEGER NOT NULL DEFAULT 0, opcode_23 INTEGER NOT NULL DEFAULT 0,
    opcode_24 INTEGER NOT NULL DEFAULT 0, opcode_25 INTEGER NOT NULL DEFAULT 0,
    opcode_26 INTEGER NOT NULL DEFAULT 0, opcode_27 INTEGER NOT NULL DEFAULT 0,
    opcode_28 INTEGER NOT NULL DEFAULT 0, opcode_29 INTEGER NOT NULL DEFAULT 0,
    opcode_2a INTEGER NOT NULL DEFAULT 0, opcode_2b INTEGER NOT NULL DEFAULT 0,
    opcode_2c INTEGER NOT NULL DEFAULT 0, opcode_2d INTEGER NOT NULL DEFAULT 0,
    opcode_2e INTEGER NOT NULL DEFAULT 0, opcode_2f INTEGER NOT NULL DEFAULT 0,
    opcode_30 INTEGER NOT NULL DEFAULT 0, opcode_31 INTEGER NOT NULL DEFAULT 0,
    opcode_32 INTEGER NOT NULL DEFAULT 0, opcode_33 INTEGER NOT NULL DEFAULT 0,
    opcode_34 INTEGER NOT NULL DEFAULT 0, opcode_35 INTEGER NOT NULL DEFAULT 0,
    opcode_36 INTEGER NOT NULL DEFAULT 0, opcode_37 INTEGER NOT NULL DEFAULT 0,
    opcode_38 INTEGER NOT NULL DEFAULT 0, opcode_39 INTEGER NOT NULL DEFAULT 0,
    opcode_3a INTEGER NOT NULL DEFAULT 0, opcode_3b INTEGER NOT NULL DEFAULT 0,
    opcode_3c INTEGER NOT NULL DEFAULT 0, opcode_3d INTEGER NOT NULL DEFAULT 0,
    opcode_3e INTEGER NOT NULL DEFAULT 0, opcode_3f INTEGER NOT NULL DEFAULT 0,
    opcode_40 INTEGER NOT NULL DEFAULT 0, opcode_41 INTEGER NOT NULL DEFAULT 0,
    opcode_42 INTEGER NOT NULL DEFAULT 0, opcode_43 INTEGER NOT NULL DEFAULT 0,
    opcode_44 INTEGER NOT NULL DEFAULT 0, opcode_45 INTEGER NOT NULL DEFAULT 0,
    opcode_46 INTEGER NOT NULL DEFAULT 0, opcode_47 INTEGER NOT NULL DEFAULT 0,
    opcode_48 INTEGER NOT NULL DEFAULT 0, opcode_49 INTEGER NOT NULL DEFAULT 0,
    opcode_4a INTEGER NOT NULL DEFAULT 0, opcode_4b INTEGER NOT NULL DEFAULT 0,
    opcode_4c INTEGER NOT NULL DEFAULT 0, opcode_4d INTEGER NOT NULL DEFAULT 0,
    opcode_4e INTEGER NOT NULL DEFAULT 0, opcode_4f INTEGER NOT NULL DEFAULT 0,
    opcode_50 INTEGER NOT NULL DEFAULT 0, opcode_51 INTEGER NOT NULL DEFAULT 0,
    opcode_52 INTEGER NOT NULL DEFAULT 0, opcode_53 INTEGER NOT NULL DEFAULT 0,
    opcode_54 INTEGER NOT NULL DEFAULT 0, opcode_55 INTEGER NOT NULL DEFAULT 0,
    opcode_56 INTEGER NOT NULL DEFAULT 0, opcode_57 INTEGER NOT NULL DEFAULT 0,
    opcode_58 INTEGER NOT NULL DEFAULT 0, opcode_59 INTEGER NOT NULL DEFAULT 0,
    opcode_5a INTEGER NOT NULL DEFAULT 0, opcode_5b INTEGER NOT NULL DEFAULT 0,
    opcode_5c INTEGER NOT NULL DEFAULT 0, opcode_5d INTEGER NOT NULL DEFAULT 0,
    opcode_5e INTEGER NOT NULL DEFAULT 0, opcode_5f INTEGER NOT NULL DEFAULT 0,
    opcode_60 INTEGER NOT NULL DEFAULT 0, opcode_61 INTEGER NOT NULL DEFAULT 0,
    opcode_62 INTEGER NOT NULL DEFAULT 0, opcode_63 INTEGER NOT NULL DEFAULT 0,
    opcode_64 INTEGER NOT NULL DEFAULT 0, opcode_65 INTEGER NOT NULL DEFAULT 0,
    opcode_66 INTEGER NOT NULL DEFAULT 0, opcode_67 INTEGER NOT NULL DEFAULT 0,
    opcode_68 INTEGER NOT NULL DEFAULT 0, opcode_69 INTEGER NOT NULL DEFAULT 0,
    opcode_6a INTEGER NOT NULL DEFAULT 0, opcode_6b INTEGER NOT NULL DEFAULT 0,
    opcode_6c INTEGER NOT NULL DEFAULT 0, opcode_6d INTEGER NOT NULL DEFAULT 0,
    opcode_6e INTEGER NOT NULL DEFAULT 0, opcode_6f INTEGER NOT NULL DEFAULT 0,
    opcode_70 INTEGER NOT NULL DEFAULT 0, opcode_71 INTEGER NOT NULL DEFAULT 0,
    opcode_72 INTEGER NOT NULL DEFAULT 0, opcode_73 INTEGER NOT NULL DEFAULT 0,
    opcode_74 INTEGER NOT NULL DEFAULT 0, opcode_75 INTEGER NOT NULL DEFAULT 0,
    opcode_76 INTEGER NOT NULL DEFAULT 0, opcode_77 INTEGER NOT NULL DEFAULT 0,
    opcode_78 INTEGER NOT NULL DEFAULT 0, opcode_79 INTEGER NOT NULL DEFAULT 0,
    opcode_7a INTEGER NOT NULL DEFAULT 0, opcode_7b INTEGER NOT NULL DEFAULT 0,
    opcode_7c INTEGER NOT NULL DEFAULT 0, opcode_7d INTEGER NOT NULL DEFAULT 0,
    opcode_7e INTEGER NOT NULL DEFAULT 0, opcode_7f INTEGER NOT NULL DEFAULT 0,
    opcode_80 INTEGER NOT NULL DEFAULT 0, opcode_81 INTEGER NOT NULL DEFAULT 0,
    opcode_82 INTEGER NOT NULL DEFAULT 0, opcode_83 INTEGER NOT NULL DEFAULT 0,
    opcode_84 INTEGER NOT NULL DEFAULT 0, opcode_85 INTEGER NOT NULL DEFAULT 0,
    opcode_86 INTEGER NOT NULL DEFAULT 0, opcode_87 INTEGER NOT NULL DEFAULT 0,
    opcode_88 INTEGER NOT NULL DEFAULT 0, opcode_89 INTEGER NOT NULL DEFAULT 0,
    opcode_8a INTEGER NOT NULL DEFAULT 0, opcode_8b INTEGER NOT NULL DEFAULT 0,
    opcode_8c INTEGER NOT NULL DEFAULT 0, opcode_8d INTEGER NOT NULL DEFAULT 0,
    opcode_8e INTEGER NOT NULL DEFAULT 0, opcode_8f INTEGER NOT NULL DEFAULT 0,
    opcode_90 INTEGER NOT NULL DEFAULT 0, opcode_91 INTEGER NOT NULL DEFAULT 0,
    opcode_92 INTEGER NOT NULL DEFAULT 0, opcode_93 INTEGER NOT NULL DEFAULT 0,
    opcode_94 INTEGER NOT NULL DEFAULT 0, opcode_95 INTEGER NOT NULL DEFAULT 0,
    opcode_96 INTEGER NOT NULL DEFAULT 0, opcode_97 INTEGER NOT NULL DEFAULT 0,
    opcode_98 INTEGER NOT NULL DEFAULT 0, opcode_99 INTEGER NOT NULL DEFAULT 0,
    opcode_9a INTEGER NOT NULL DEFAULT 0, opcode_9b INTEGER NOT NULL DEFAULT 0,
    opcode_9c INTEGER NOT NULL DEFAULT 0, opcode_9d INTEGER NOT NULL DEFAULT 0,
    opcode_9e INTEGER NOT NULL DEFAULT 0, opcode_9f INTEGER NOT NULL DEFAULT 0,
    opcode_a0 INTEGER NOT NULL DEFAULT 0, opcode_a1 INTEGER NOT NULL DEFAULT 0,
    opcode_a2 INTEGER NOT NULL DEFAULT 0, opcode_a3 INTEGER NOT NULL DEFAULT 0,
    opcode_a4 INTEGER NOT NULL DEFAULT 0, opcode_a5 INTEGER NOT NULL DEFAULT 0,
    opcode_a6 INTEGER NOT NULL DEFAULT 0, opcode_a7 INTEGER NOT NULL DEFAULT 0,
    opcode_a8 INTEGER NOT NULL DEFAULT 0, opcode_a9 INTEGER NOT NULL DEFAULT 0,
    opcode_aa INTEGER NOT NULL DEFAULT 0, opcode_ab INTEGER NOT NULL DEFAULT 0,
    opcode_ac INTEGER NOT NULL DEFAULT 0, opcode_ad INTEGER NOT NULL DEFAULT 0,
    opcode_ae INTEGER NOT NULL DEFAULT 0, opcode_af INTEGER NOT NULL DEFAULT 0,
    opcode_b0 INTEGER NOT NULL DEFAULT 0, opcode_b1 INTEGER NOT NULL DEFAULT 0,
    opcode_b2 INTEGER NOT NULL DEFAULT 0, opcode_b3 INTEGER NOT NULL DEFAULT 0,
    opcode_b4 INTEGER NOT NULL DEFAULT 0, opcode_b5 INTEGER NOT NULL DEFAULT 0,
    opcode_b6 INTEGER NOT NULL DEFAULT 0, opcode_b7 INTEGER NOT NULL DEFAULT 0,
    opcode_b8 INTEGER NOT NULL DEFAULT 0, opcode_b9 INTEGER NOT NULL DEFAULT 0,
    opcode_ba INTEGER NOT NULL DEFAULT 0, opcode_bb INTEGER NOT NULL DEFAULT 0,
    opcode_bc INTEGER NOT NULL DEFAULT 0, opcode_bd INTEGER NOT NULL DEFAULT 0,
    opcode_be INTEGER NOT NULL DEFAULT 0, opcode_bf INTEGER NOT NULL DEFAULT 0,
    opcode_c0 INTEGER NOT NULL DEFAULT 0, opcode_c1 INTEGER NOT NULL DEFAULT 0,
    opcode_c2 INTEGER NOT NULL DEFAULT 0, opcode_c3 INTEGER NOT NULL DEFAULT 0,
    opcode_c4 INTEGER NOT NULL DEFAULT 0, opcode_c5 INTEGER NOT NULL DEFAULT 0,
    opcode_c6 INTEGER NOT NULL DEFAULT 0, opcode_c7 INTEGER NOT NULL DEFAULT 0,
    opcode_c8 INTEGER NOT NULL DEFAULT 0, opcode_c9 INTEGER NOT NULL DEFAULT 0,
    opcode_ca INTEGER NOT NULL DEFAULT 0, opcode_cb INTEGER NOT NULL DEFAULT 0,
    opcode_cc INTEGER NOT NULL DEFAULT 0, opcode_cd INTEGER NOT NULL DEFAULT 0,
    opcode_ce INTEGER NOT NULL DEFAULT 0, opcode_cf INTEGER NOT NULL DEFAULT 0,
    opcode_d0 INTEGER NOT NULL DEFAULT 0, opcode_d1 INTEGER NOT NULL DEFAULT 0,
    opcode_d2 INTEGER NOT NULL DEFAULT 0, opcode_d3 INTEGER NOT NULL DEFAULT 0,
    opcode_d4 INTEGER NOT NULL DEFAULT 0, opcode_d5 INTEGER NOT NULL DEFAULT 0,
    opcode_d6 INTEGER NOT NULL DEFAULT 0, opcode_d7 INTEGER NOT NULL DEFAULT 0,
    opcode_d8 INTEGER NOT NULL DEFAULT 0, opcode_d9 INTEGER NOT NULL DEFAULT 0,
    opcode_da INTEGER NOT NULL DEFAULT 0, opcode_db INTEGER NOT NULL DEFAULT 0,
    opcode_dc INTEGER NOT NULL DEFAULT 0, opcode_dd INTEGER NOT NULL DEFAULT 0,
    opcode_de INTEGER NOT NULL DEFAULT 0, opcode_df INTEGER NOT NULL DEFAULT 0,
    opcode_e0 INTEGER NOT NULL DEFAULT 0, opcode_e1 INTEGER NOT NULL DEFAULT 0,
    opcode_e2 INTEGER NOT NULL DEFAULT 0, opcode_e3 INTEGER NOT NULL DEFAULT 0,
    opcode_e4 INTEGER NOT NULL DEFAULT 0, opcode_e5 INTEGER NOT NULL DEFAULT 0,
    opcode_e6 INTEGER NOT NULL DEFAULT 0, opcode_e7 INTEGER NOT NULL DEFAULT 0,
    opcode_e8 INTEGER NOT NULL DEFAULT 0, opcode_e9 INTEGER NOT NULL DEFAULT 0,
    opcode_ea INTEGER NOT NULL DEFAULT 0, opcode_eb INTEGER NOT NULL DEFAULT 0,
    opcode_ec INTEGER NOT NULL DEFAULT 0, opcode_ed INTEGER NOT NULL DEFAULT 0,
    opcode_ee INTEGER NOT NULL DEFAULT 0, opcode_ef INTEGER NOT NULL DEFAULT 0,
    opcode_f0 INTEGER NOT NULL DEFAULT 0, opcode_f1 INTEGER NOT NULL DEFAULT 0,
    opcode_f2 INTEGER NOT NULL DEFAULT 0, opcode_f3 INTEGER NOT NULL DEFAULT 0,
    opcode_f4 INTEGER NOT NULL DEFAULT 0, opcode_f5 INTEGER NOT NULL DEFAULT 0,
    opcode_f6 INTEGER NOT NULL DEFAULT 0, opcode_f7 INTEGER NOT NULL DEFAULT 0,
    opcode_f8 INTEGER NOT NULL DEFAULT 0, opcode_f9 INTEGER NOT NULL DEFAULT 0,
    opcode_fa INTEGER NOT NULL DEFAULT 0, opcode_fb INTEGER NOT NULL DEFAULT 0,
    opcode_fc INTEGER NOT NULL DEFAULT 0, opcode_fd INTEGER NOT NULL DEFAULT 0,
    opcode_fe INTEGER NOT NULL DEFAULT 0, opcode_ff INTEGER NOT NULL DEFAULT 0,

    -- index 256: TxValues.CALL_ORDINAL_IDX
    call_ordinal INTEGER NOT NULL,

    -- index 257: TxValues.CALL_GAS_USED (net gas consumed by this call frame)
    call_gas_used INTEGER NOT NULL DEFAULT 0,

    -- index 258: TxValues.CALL_SUCCESS (1 = success, 0 = failure)
    call_success INTEGER NOT NULL DEFAULT 0,

    -- index 259: TxValues.CALL_MEMORY_WORD_SIZE
    call_memory_word_size INTEGER NOT NULL DEFAULT 0,

    -- index 260: TxValues.EXP_OPERATION_BYTES (also CALL_PRECOMPILE_BASE + 0x00)
    exp_operation_bytes INTEGER NOT NULL DEFAULT 0,

    -- indices 261..270: TxValues.CALL_PRECOMPILE_BASE + precompile address byte (0x01..0x0a)
    call_precompile_01 INTEGER NOT NULL DEFAULT 0,
    call_precompile_02 INTEGER NOT NULL DEFAULT 0,
    call_precompile_03 INTEGER NOT NULL DEFAULT 0,
    call_precompile_04 INTEGER NOT NULL DEFAULT 0,
    call_precompile_05 INTEGER NOT NULL DEFAULT 0,
    call_precompile_06 INTEGER NOT NULL DEFAULT 0,
    call_precompile_07 INTEGER NOT NULL DEFAULT 0,
    call_precompile_08 INTEGER NOT NULL DEFAULT 0,
    call_precompile_09 INTEGER NOT NULL DEFAULT 0,
    call_precompile_0a INTEGER NOT NULL DEFAULT 0,

    -- index 271: TxValues.CALL_PRECOMPILE_OTHERS
    call_precompile_others INTEGER NOT NULL DEFAULT 0,

    -- indices 272..276: precompile workload counters
    call_precompile_sha256_words_processed INTEGER NOT NULL DEFAULT 0,
    call_precompile_ripemd160_words_processed INTEGER NOT NULL DEFAULT 0,
    call_precompile_id_words_processed INTEGER NOT NULL DEFAULT 0,
    call_precompile_ec_pairing_params_processed INTEGER NOT NULL DEFAULT 0,
    call_precompile_blake2bf_rounds_processed INTEGER NOT NULL DEFAULT 0,

    -- indices 277..280: EIP-2929-style access counters
    access_address_cold_count INTEGER NOT NULL DEFAULT 0,
    access_address_warm_count INTEGER NOT NULL DEFAULT 0,
    access_storage_cold_count INTEGER NOT NULL DEFAULT 0,
    access_storage_warm_count INTEGER NOT NULL DEFAULT 0,

    -- index 281: TxValues.KECCAK256_WORDS_PROCESSED
    keccak256_words_processed INTEGER NOT NULL DEFAULT 0
);
